02-19 14:47:30 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Das Objekt wurde bereits geschlossen
The object is already closed [90007-164]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1393)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1371)
	at org.h2.jdbc.JdbcConnection.createStatement(JdbcConnection.java:191)
	at com.thebrain.common.b.d.H(dwf:239)
	at com.thebrain.common.b.d.H(dwf:92)
	at com.thebrain.common.b.d.H(dwf:203)
	at com.thebrain.personal.a.a.g.A(yld:921)
	at com.thebrain.c.e.o.F(odg:435)
	at com.thebrain.personal.a.a.r.d(ihd:268)
	at com.thebrain.personal.view.pl.H(xfd:3936)
	at com.thebrain.personal.view.pl.DA(xfd:4263)
	at com.thebrain.personal.view.pl.W(xfd:3875)
	at com.thebrain.personal.view.kc.run(xfd:4718)
	at java.lang.Thread.run(Thread.java:744)
